name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']

    name: PHP ${{ matrix.php-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        run: vendor/bin/phpunit

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: php-actions/composer@v6

      - name: PHPStan
        run: vendor/bin/phpstan analyse

  cs-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: php-actions/composer@v6

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
